name = "fragrant-thunder-7349"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Aponta para o worker gerado
main = ".vercel/output/_worker.js"

# Configuração de Assets (substitui o antigo [site])
[assets]
directory = ".vercel/output/static"
binding = "ASSETS"